// Package services contains trusted internal service composition,
// automation support, moderation helpers, and shared internal workflow logic.
//
// focodebase/fobackend/internal/services/errors.go
package services

import "errors"

var (
	ErrInvalidServiceConfiguration                                    = errors.New("invalid internal service configuration")
	ErrNilContext                                                     = errors.New("context must not be nil")
	ErrNilOffer                                                       = errors.New("offer must not be nil")
	ErrInvalidDecimal                                                 = errors.New("invalid decimal value")
	ErrOfferMetadataIncomplete                                        = errors.New("offer metadata incomplete")
	ErrStatusNameRequired                                             = errors.New("status name cannot be empty")
	ErrMaintenanceJobDisabled                                         = errors.New("system maintenance notification job is disabled")
	ErrInvalidMerchantProgramSubscriptionTransition                   = errors.New("invalid merchant program subscription transition")
	ErrUnsupportedMerchantProgramSubscriptionTransition               = errors.New("unsupported merchant program subscription transition")
	ErrMerchantBillableEventSourceNotFound                            = errors.New("merchant billable event authoritative source not found")
	ErrMerchantBillableEventSourceIneligible                          = errors.New("merchant billable event authoritative source is ineligible")
	ErrMerchantPlatformCreditApplicationFeeCalculationNotApproved     = errors.New("merchant platform credit application requires an approved fee calculation")
	ErrMerchantPlatformCreditApplicationExceedsObligation             = errors.New("merchant platform credit application would exceed the fee calculation obligation")
	ErrMerchantPlatformCreditApplicationMerchantMismatch              = errors.New("merchant platform credit account and fee calculation belong to different merchants")
	ErrMerchantFutureOfferingServiceTermOperatingRangeInvalid         = errors.New("merchant future offering service term operating range configuration is invalid")
	ErrMerchantFutureOfferingServiceTermDurationOutsideOperatingRange = errors.New("merchant future offering service term duration is outside the currently permitted operating range")
	ErrMerchantFutureOfferingServicePeriodInputInvalid                = errors.New("invalid merchant future offering service period orchestration request")
	ErrMerchantFutureOfferingServicePeriodServiceTermScopeMismatch    = errors.New("merchant future offering service term was not found within the specified future offering")
	ErrMerchantFutureOfferingServicePeriodServiceTermNotEstablished   = errors.New("merchant future offering service term is not established")
	ErrMerchantFutureOfferingServicePeriodCreationNotYetEligible      = errors.New("merchant future offering service period creation boundary has not yet been reached")
	ErrMerchantFutureOfferingServicePeriodServiceTermComplete         = errors.New("merchant future offering service term has no remaining service period")
	ErrMerchantFutureOfferingServicePeriodInvalidState                = errors.New("merchant future offering service period orchestration encountered invalid state")
	ErrMerchantFutureOfferingBillingPeriodInputInvalid                = errors.New("invalid merchant future offering billing period orchestration request")
	ErrMerchantFutureOfferingBillingPeriodServiceTermScopeMismatch    = errors.New("merchant future offering service term was not found within the specified future offering")
	ErrMerchantFutureOfferingBillingPeriodAlreadyExists               = errors.New("merchant future offering billing period already exists")
	ErrMerchantFutureOfferingBillingPeriodTermExhausted               = errors.New("merchant future offering service term has no remaining billing period")
	ErrMerchantFutureOfferingBillingPeriodCreationNotYetEligible      = errors.New("merchant future offering billing period creation boundary has not yet been reached")
	ErrMerchantFutureOfferingBillingPeriodConcurrentCreation          = errors.New("merchant future offering billing period creation encountered a concurrent persistence conflict")
	ErrMerchantFutureOfferingBillingPeriodEventConflict               = errors.New("merchant future offering billing period outbox event conflict")
	ErrMerchantFutureOfferingBillingPeriodInvalidState                = errors.New("merchant future offering billing period orchestration encountered invalid state")
	ErrUsersSignupInputInvalid                                        = errors.New("invalid users signup input")
	ErrUsersActivationInitialization                                  = errors.New("user account created but activation initialization failed")
	ErrUsersAuthenticationInputInvalid                                = errors.New("invalid user authentication input")
	ErrUsersActorRequired                                             = errors.New("acting user ID is required")
	ErrUsersTargetRequired                                            = errors.New("target user ID is required")
	ErrUsersRefreshTokenRequired                                      = errors.New("refresh token is required")
	ErrUsersSessionInvalid                                            = errors.New("user session is invalid or expired")
	ErrUsersSessionOwnershipMismatch                                  = errors.New("refresh token does not belong to the acting user")
	ErrUsersAccountNotEligible                                        = errors.New("user account is not eligible for this operation")
	ErrUsersPasswordAlreadyEstablished                                = errors.New("user password is already established")
	ErrUsersPasswordEstablishmentConflict                             = errors.New("initial password establishment encountered a concurrent state conflict")
	ErrUsersCurrentPasswordIncorrect                                  = errors.New("services: current password is incorrect")
	ErrUsersPasswordConfirmationMismatch                              = errors.New("services: new password and confirmation do not match")
	ErrUsersPasswordNotEstablished                                    = errors.New("services: account has no password established")
	ErrUsersPasswordUnchanged                                         = errors.New("services: new password must differ from the current password")
	ErrMerchantActorRequired                                          = errors.New("merchant service: actor user ID is required")
	ErrMerchantResourceRequired                                       = errors.New("merchant service: merchant ID is required")
	ErrMerchantAccessForbidden                                        = errors.New("merchant service: actor is not authorized for this merchant")

	// Administrative governance. GovernanceDenialCode maps each of these to
	// the stable client-facing code.
	ErrGovernanceInputInvalid                = errors.New("governance: invalid request")
	ErrGovernanceSelfTarget                  = errors.New("governance: administrators cannot govern their own standing")
	ErrGovernanceInsufficientAuthority       = errors.New("governance: actor lacks authority over the target")
	ErrGovernanceRootProtected               = errors.New("governance: the Root Super Admin is protected")
	ErrGovernanceTargetNotFound              = errors.New("governance: target account not found")
	ErrGovernanceTargetIneligible            = errors.New("governance: target account is not eligible")
	ErrGovernanceInvalidTransition           = errors.New("governance: transition is not valid for the target's standing")
	ErrGovernanceAdministratorAccount        = errors.New("governance: administrative standing must be revoked before the account is closed")
	ErrGovernanceAdministratorSelfClosure    = errors.New("governance: an administrator cannot close their own account")
	ErrGovernanceReauthenticationFailed      = errors.New("governance: re-authentication failed")
	ErrGovernanceReauthenticationUnavailable = errors.New("governance: re-authentication requires an account password")
	ErrGovernanceConfirmationMismatch        = errors.New("governance: confirmation does not match the target account")
	ErrRootBootstrapConflict                 = errors.New("governance: a different Root Super Admin is already established")
	ErrRootBootstrapAccountNotFound          = errors.New("governance: bootstrap account not found")
	ErrRootBootstrapAccountIneligible        = errors.New("governance: bootstrap account is not active (email not confirmed or deactivated)")
)
